### ISSUE TITLE
Local Connection Fails

### ISSUE THREAD

**Issue by techgerm** [planetscale/database-js#104]
## Scenario
1. I run `pscale connect galaxy --port 3309` locally to connect to my PlanetScale DB
1. I attempt to connect my [T3 app](https://github.com/t3-oss/create-t3-app) using `import { connect } from "@planetscale/database";`

## Problem
1. When I use `url` to connect to my local db connection, it does not use the specified port - instead is uses port `443`:
```
const connection = connect({
  url: "mysql://root@127.0.0.1:3309"
});
```
![Screenshot 2023-04-09 at 8 13 19 PM](https://user-images.githubusercontent.com/38846104/230819095-853d4332-cef6-4e8b-8fee-b030db34c0c2.png)

2. When I use `host` & `username` to connect to my local db connection, it uses the correct port but it fails with a `ERR_SSL_WRONG_VERSION_NUMBER` status code
```
const connection = connect({
  host: "127.0.0.1:3309",
  username: "root"
});
```
![Screenshot 2023-04-09 at 8 12 30 PM](https://user-images.githubusercontent.com/38846104/230819285-aa205ce3-3e74-4cf5-a21d-17db0e1dd350.png)

I'd love to be able to use this package instead of `prisma` for my next project.

Anything that can be done to help here would be greatly appreciated!

**Comment by mattrobenolt** [comment]
This is correct. We don't have an equivalent yet since this driver speaks HTTP and `pscale connect` is mysql. So in this case, it's not a deficit of database-js, just a fundamental difference in protocol.  On Apr 9, 2023, at 20:29, Germán Pineda ***@***.***> wrote:﻿
Scenario

I run pscale connect galaxy --port 3309 locally to connect to my PlanetScale DB
I attempt to connect my T3 app using import { connect } from ***@***.***/database";

Problem

When I use url to connect to my local db connection, it does not use the specified port - instead is uses port 443:

const connection = connect({
  url: ***@***.***:3309"
});



When I use host & username to connect to my local db connection, it uses the correct port but it fails with a ERR_SSL_WRONG_VERSION_NUMBER status code

const connection = connect({
  host: "127.0.0.1:3309",
  username: "root"
});


I'd love to be able to use this package instead of prisma for my next project.
Anything that can be done to help here would be greatly appreciated!

**Comment by techgerm** [comment]
@mattrobenolt thanks for the quick response and clarification!
In that case, do you know how I can specify a DB branch in this configuration?

**Comment by mattrobenolt** [comment]
When you create credentials, they're bound to a branch. So you'd just create credentials for the branch you want, and it'll work. Are you observing something differently?

**Comment by techgerm** [comment]
Ah that's my mistake, didn't realize that was the case. Thanks again for your help!

Out of curiosity, are there any future plans to bridge the protocols?

**Comment by mattrobenolt** [comment]
Bride them how? I have some plans. 👀 But curious what you have in mind.

**Comment by techgerm** [comment]
Hmm let me give it some thought and I'll get back to you!

**Comment by janpio** [comment]
Related: https://github.com/planetscale/database-js/issues/135
