### ISSUE TITLE
LAST_INSERTED_ID comes back as string

### ISSUE THREAD

**Issue by arackaf** [planetscale/database-js#86]
The types returned by the http driver usually line up well with what's in the db, but for some reason LAST_INSERT_ID comes back as a string

```js
const newId = await tx.execute("SELECT LAST_INSERT_ID() as id");
console.log(newId.rows, typeof newId.rows[0].id);
```

which prints 

<img width="204" alt="image" src="https://user-images.githubusercontent.com/11261266/222196274-02ef373b-bf29-41a9-876d-64e4a747132a.png">

**Comment by iheanyi** [comment]
Hello @arackaf! Thanks for the issue.

This is actually lining up with what's returned by `LAST_INSERT_ID`. According to the [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_last-insert-id), the type of `LAST_INSERT_ID()` is an unsigned big integer. Within our driver, we handled all 64-bit integers as strings, because of JavaScript limitations. This way, the user can handle that returned `BigInt` in their own way. Let me know if you have anymore questions!

**Comment by arackaf** [comment]
Ohhhh that makes sense. JS numbers are 64 bit floating point, so I'm assuming the problem is that a 64 bit integer can exceed that, and cause overflow? 

Sorry for the superfluous issue, but hopefully it'll help someone down the line

**Comment by mattrobenolt** [comment]
Yeah, and more specifically because the API itself is JSON, you can't correctly represent a 64 bit integer as a Number in JSON. So it's common to handle them as strings so the language can re-interpret them into a more... correct type.

Does JavaScript even have a native 64 bit integer we can use reliably and do the transformation automatically?
